AWSTemplateFormatVersion: 2010-09-09
Description: Payola Api Distribution Stack

Resources:
  PayolaRestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: PayolaRestApi
      Body: # Flag serves as a substituion placeholder
        OPENAPI

  CreateClaim:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: rust
      Handler: handler.createClaim
#      Role:

  GetClaimStatus:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: rust
      Handler: handler.getClaimStatus
#      Role:

  UpdateClaim:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: rust
      Handler: handler.updateClaim
#      Role:

  StoreClaim:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: rust
      Handler: handler.storeClaim
#      Role:

  GetBalance:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: rust
      Handler: handler.getBalance
#      Role:

  GetConfig:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: rust
      Handler: handler.getConfig
#      Role:
