AWSTemplateFormatVersion: 2010-09-09
Description: | Payola Api Distribution Stack

Resources:
  PayolaRestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: PayolaRestApi
      # Body: Inject openapi.yml or specify file reference


  CreateClaim:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: rust
      Handler: handler.createClaim

  GetClaimStatus:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: rust
      Handler: handler.getClaimStatus

  UpdateClaim:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: rust
      Handler: handler.updateClaim

  StoreClaim:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: rust
      Handler: handler.storeClaim

  GetBalance:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: rust
      Handler: handler.getBalance

  GetConfig:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: rust
      Handler: handler.getConfig
