AWSTemplateFormatVersion: 2010-09-09
Resources:
  PayolaRestApi:
    Type: AWS:ApiGateway:RestApi
    Properties:
      Name: PayolaRestApi
      # BodyS3Location:


  CreateClaim:
    Type: AWS:Lambda:Function
    Properties:
      Runtime: rust
      Handler: handler.createClaim
      # events:
      #   - http:
      #       path: /claim/{id}
      #       method: post
      #       request:
      #         parameters:
      #           paths:
      #             id: true

  GetClaimStatus:
    Type: AWS:Lambda:Function
    Properties:
      Runtime: rust
      Handler: handler.getClaimStatus
      # events:
      #   - http:
      #       path: /claim/{id}
      #       method: head
      #       request:
      #         parameters:
      #           paths:
      #             id: true

  UpdateClaim:
    Type: AWS:Lambda:Function
    Properties:
      Runtime: rust
      Handler: handler.updateClaim
      # events:
      #   - http:
      #       path: /claim/store/{id,msisdn,amount,currency}
      #       method: put

  StoreClaim:
    Type: AWS:Lambda:Function
    Properties:
      Runtime: rust
      Handler: handler.storeClaim
      # events:
      #   - http:
      #       path: /claim/store/{id,msisdn,amount,currency}
      #       method: post

  GetBalance:
    Type: AWS:Lambda:Function
    Properties:
      Runtime: rust
      Handler: handler.getBalance
      # events:
      #   - http:
      #       path: /gas-provider/balance/{id}
      #       method: post
      #       request:
      #         parameters:
      #           paths:
      #             id: true

  GetConfig:
    Type: AWS:Lambda:Function
    Properties:
      Runtime: rust
      Handler: handler.getConfig
      # events:
      #   - http:
      #       path: /devices/config/
      #       method: get
