AWSTemplateFormatVersion: 2010-09-09
Description: Payola API Stack

Metadata:
  "AWS::Cloudformation::Interface":
    ParameterGroups:
      - Label:
          default: Meta
        Parameters:
          - Environment
      - Label:
          default: API
        Parameters:
          - FunctionMemorySize
          - FunctionTimeout
          - GetBalanceHandlerName

Parameters:
  Environment:
    Description: Environment name - test/prod
    AllowedPattern: "^(test|prod)$"
    Type: String

  FunctionMemorySize:
    Description: how many megabytes of ram to allocate for the lambda
    Type: Number
    Default: 128

  FunctionTimeout:
    Description: Lambda timeout in seconds
    Type: Number
    Default: 3

  GetBalanceHandlerName:
    Description: Lambda function name for the 'get balance' handler
    AllowedPattern: "^[a-z0-9]+[a-z0-9-]+[a-z0-9]+$"
    Type: String

Resources:
  RestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub ${AWS::StackName}-restapi-${Environment}
      Tags:
        - Key: "payola:name"
          Value: !Sub ${AWS::StackName}-restapi-${Environment}

  BalanceResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt RestApi.RootResourceId
      PathPart: balance
      RestApiId: !Ref RestApi

  GetBalanceHandlerPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - RestApi
      - GetBalanceHandler
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt GetBalanceHandler.Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RestApi}/*/*

  CreateGetBalanceMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      ApiKeyRequired: false
      AuthorizationType: NONE
      HttpMethod: GET
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub
          - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetBalanceHandlerArn}/invocations
          - GetBalanceHandlerArn: !GetAtt GetBalanceHandler.Arn
      MethodResponses:
        - StatusCode: "200"
        - StatusCode: "400"
        - StatusCode: "401"
        - StatusCode: "404"
        - StatusCode: "500"
      ResourceId: !Ref BalanceResource
      RestApiId: !Ref RestApi

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaExecutionPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
              # TODO: narrow down permissions with a lambda exec role for every handler
                Action:
                  - dynamodb:*
                  - lambda:*
                Resource: "*"

  GetBalanceHandler:
    Type: AWS::Lambda::Function
    Properties:
      Tags:
        - Key: "payola:name"
          Value: !Ref GetBalanceHandlerName
      Code:
        ZipFile: |
          exports.handler = async function () {
            var response = JSON.stringify({body: "Hello World!"})
            return response
          }
      Runtime: nodejs12.x
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      MemorySize: !Ref FunctionMemorySize
      Timeout: !Ref FunctionTimeout

Outputs:
  ApiBaseURL:
    Description: "API Base URL"
    Value: !Sub https://${RestApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}

  LambdaArn:
    Description: "Endpoint of the GetBalanceHandler lambda function"
    Value: !GetAtt GetBalanceHandler.Arn
