name: continous integration

on: push

env:
  AWS_REGION: us-east-1
  # NOTE: CFN_TEMPLATES must be newline-delimited string indicating
  # cloudformation template files to validate
  CFN_TEMPLATES: ".github/cd_setup.yml\n./compute/stack.yml"
  OPEN_API_SPEC: compute/openapi.yml

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: clone the repo
        uses: actions/checkout@v2.3.1

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: validate the open api spec
        uses: mpetrunic/swagger-cli-action@v1.0.0
        with:
          command: "validate ${{ env.OPEN_API_SPEC }}"

      - name: validate all cloudformation templates
        run: |
          printf "${{ env.CFN_TEMPLATES }}" | while read template; do
            aws cloudformation validate-template \
              --template-body="file://$template"
          done
